---
# tasks file for infrared-overcloud

---
- name: add infrared overcloud plugin
  shell: |
    source {{infrared_venv }}
    infrared plugin add plugins/tripleo-overcloud
  args:
   chdir: "{{ infrared_dir }}"
  ignore_errors: true
 
- name: copy extra templates
  copy:
    src: oc_extra_templates.yaml
    dest: "{{ infrared_dir}/plugins/tripleo-overcloud/vars/deployment/files/"

- name: install overcloud
  shell: |
    source {{ infrared_venv }}
    infrared tripleo-overcloud --version {{ openstack.version }} --introspect yes --tagging yes --deploy yes --post yes --deployment-files virt --controller-nodes {{ openstack.controller.count }} --compute-nodes {{ openstack.computes.count }} --overcloud-templates {{ infrared_dir}/plugins/tripleo-overcloud/vars/deployment/files/oc_extra_templates.yml --deployment-timeout 180 --extra-deploy-params="-n /home/stack/network_data.yaml" 
  args:
    chdir: "{{ infrared_dir }}"
  ignore_errors: true
