apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: compute-node
  labels:
    app: compute-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compute-node
  template:
    metadata:
      labels:
        app: compute-node
    spec:
      containers:
      - image: 192.168.24.1:8787/compute_node
        name: compute-node
