---
# tasks file for infrared-provision
- name: add infrared virsh plugin
  shell: |
    source {{ infrared_venv }}
    infrared plugin add plugins/virsh
  args:
    chdir: "{{ infrared_dir }}"
  ignore_errors: true
 
- name: provision vms
  shell: |
    source {{ infrared_venv }}
    infrared virsh --host-address {{ infrared.hypervisor }} --host-key {{ infrared.host_key }} --host-memory-overcommit {{ infrared.overcommit }} --topology-nodes "undercloud:{{ openstack.undercloud.count }},controller:{{ openstack.controller.count }},compute:{{ openstack.compute.count }},openshift-master:{{ openshift.master.count }},openshift-worker:{{ openshift.worker.count }},openshift-infra:{{ openshift.infra.count }},openshift-tester:{{ openshift.tester.count }}"
  args:
    chdir: "{{ infrared_dir }}"
