release: rocky
build: current-tripleo-rdo
delorean_url: "https://trunk.rdoproject.org/centos7-{{release}}/{{build}}/delorean.repo"
delorean_deps_url: "https://trunk.rdoproject.org/centos7-{{release}}/delorean-deps.repo"

cluster_cidr: 10.128.0.0/14
