release: rocky
build: current-tripleo-rdo
delorean_url: "https://trunk.rdoproject.org/centos7-{{release}}/{{build}}/delorean.repo"
delorean_deps_url: "https://trunk.rdoproject.org/centos7-{{release}}/delorean-deps.repo"

workers_ips: [172.17.1.19, 172.17.1.10]
controllers_ips: [172.17.1.160, 172.17.1.170]
controllers_cluster_ips: [10.131.0.8, 10.131.0.9]
cluster_cidr: 10.128.0.0/14
