---
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: set infrared facts
      set_fact:
        infrared_dir: "{{ lookup('env','WORKSPACE') }}/infrared"
        infrared_venv: "{{ lookup('env','WORKSPACE') }}/infrared/.venv/bin/activate"
  roles:
    - infrared-openshift
    - infrared-overcloud

