---
- hosts: localhost
  connection: local
  become: true
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: set infrared facts
      set_fact:
        infrared_dir: "{{ lookup('env','WORKSPACE') }}/infrared"
        infrared_venv: "{{ lookup('env','WORKSPACE') }}/infrared/.venv/bin/activate"
        infrared_workspace: "{{ lookup('env', 'HOME') }}/.infrared/"
      tags:
        - always
  roles:
    - { role: infrared-install, tags: [setup] }
    - { role: infrared-provision, tags: [setup] }
    - { role: infrared-hosts, tags: [setup] }
    - { role: infrared-undercloud, tags: [setup] }

- hosts: undercloud
  vars_file:
    - vars/main.yml
   roles:
     - role: prepare-templates
