---
# tasks file for infrared-undercloud
- name: add infrared undercloud plugin
  shell: |
    source {{infrared_venv }}
    infrared plugin add plugins/tripleo-undercloud
  args:
    chdir: "{{ infrared_dir }}"
  ignore_errors: true

- name: install undercloud
  shell: | 
    source {{ infrared_venv }}
    infrared tripleo-undercloud --version {{ openstack.version }} --images-task rpm --build {{ openstack.build }}
  args:
    chdir: "{{ infrared_dir }}"

